from fastapi import APIRouter, HTTPException
from fastapi.responses import Response, JSONResponse
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
from datetime import datetime, timezone
import json

router = APIRouter(prefix="/export", tags=["Export Engine"])


class ExportRequest(BaseModel):
    workflow_id: str = Field(..., description="Workflow execution ID")
    title: str = Field(..., description="Document title")
    content: str = Field(..., description="Markdown content string")
    model: Optional[str] = Field("llama3:latest", description="Model used")
    include_metadata: bool = Field(True, description="Whether to include YAML metadata header")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


@router.post("/markdown")
async def export_markdown(request: ExportRequest):
    """
    Exports content as formatted Markdown (.md) with optional YAML metadata frontmatter.
    """
    metadata_header = ""
    if request.include_metadata:
        now_str = datetime.now(timezone.utc).isoformat()
        metadata_header = (
            "---\n"
            f"title: \"{request.title}\"\n"
            f"workflow_id: \"{request.workflow_id}\"\n"
            f"exported_at: \"{now_str}\"\n"
            f"model: \"{request.model}\"\n"
            "platform: \"AgentFlow Open-Source AI Orchestrator\"\n"
            "---\n\n"
        )

    final_md = metadata_header + request.content
    filename = f"{request.title.lower().replace(' ', '_')}_{request.workflow_id}.md"

    return Response(
        content=final_md,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/json")
async def export_json(request: ExportRequest):
    """
    Exports full execution data as a formatted JSON (.json) payload.
    """
    payload = {
        "export_metadata": {
            "title": request.title,
            "workflow_id": request.workflow_id,
            "exported_at": datetime.now(timezone.utc).isoformat(),
            "model": request.model,
            "platform": "AgentFlow AI Orchestration Platform",
        },
        "content": request.content,
        "additional_metadata": request.metadata,
    }

    filename = f"{request.title.lower().replace(' ', '_')}_{request.workflow_id}.json"

    return Response(
        content=json.dumps(payload, indent=2),
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/pdf")
async def export_pdf_html(request: ExportRequest):
    """
    Generates an executive HTML print template optimized for browser PDF saving.
    """
    now_str = datetime.now(timezone.utc).strftime("%B %d, %Y - %H:%M UTC")

    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{request.title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #1e293b;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
        }}
        .header-meta {{
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 15px;
            margin-bottom: 30px;
        }}
        .header-meta h1 {{
            margin: 0 0 10px 0;
            color: #0f172a;
            font-size: 24px;
        }}
        .meta-grid {{
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 8px;
            font-size: 12px;
            color: #64748b;
        }}
        .content {{
            font-size: 14px;
        }}
        pre, code {{
            background: #f1f5f9;
            padding: 4px 8px;
            border-radius: 4px;
            font-family: monospace;
            font-size: 12px;
        }}
        .footer {{
            margin-top: 50px;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
            font-size: 11px;
            color: #94a3b8;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="header-meta">
        <h1>{request.title}</h1>
        <div class="meta-grid">
            <div><strong>Workflow ID:</strong> {request.workflow_id}</div>
            <div><strong>Model:</strong> {request.model}</div>
            <div><strong>Export Date:</strong> {now_str}</div>
            <div><strong>Platform:</strong> AgentFlow AI Engine</div>
        </div>
    </div>

    <div class="content">
        <pre style="white-space: pre-wrap; background: transparent; font-family: inherit; font-size: inherit;">
{request.content}
        </pre>
    </div>

    <div class="footer">
        Generated by AgentFlow Open-Source AI Orchestration Platform
    </div>

    <script>
        window.onload = function() {{ window.print(); }};
    </script>
</body>
</html>"""

    return Response(
        content=html_content,
        media_type="text/html",
    )
