-- Enable RLS on legacy tables for total database security
ALTER TABLE IF EXISTS public.flows ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.agent_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.execution_logs ENABLE ROW LEVEL SECURITY;
